<?php
if( function_exists('acf_add_local_field_group') ):

    acf_add_local_field_group(array(
        'key' => 'group_5ee7cf9b0db50',
        'title' => 'Events',
        'fields' => array(
            array(
                'key' => 'field_5ee7cfa118792',
                'label' => 'Events & Speaking Engagments',
                'name' => 'events',
                'type' => 'repeater',
                'instructions' => 'For adding speaking events, conferences, book signings, and other public appearances',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'collapsed' => 'field_5ee7cfd218793',
                'min' => 0,
                'max' => 0,
                'layout' => 'block',
                'button_label' => 'Add Event',
                'sub_fields' => array(
                    array(
                        'key' => 'field_5ee7cfd218793',
                        'label' => 'Event Name',
                        'name' => 'event_name',
                        'type' => 'text',
                        'instructions' => 'The name of the event',
                        'required' => 1,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                    ),
                    array(
                        'key' => 'field_5ee7d00118794',
                        'label' => 'Event Description',
                        'name' => 'event_description',
                        'type' => 'wysiwyg',
                        'instructions' => 'A description of the overall event highlighting your particular role.',
                        'required' => 1,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'tabs' => 'all',
                        'toolbar' => 'full',
                        'media_upload' => 0,
                        'delay' => 0,
                    ),
                    array(
                        'key' => 'field_5ee7d2441879d',
                        'label' => 'Start Date/Time',
                        'name' => 'start_datetime',
                        'type' => 'date_time_picker',
                        'instructions' => '',
                        'required' => 1,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'display_format' => 'F j, Y g:i a',
                        'return_format' => 'U',
                        'first_day' => 0,
                    ),
                    array(
                        'key' => 'field_5ee7d26e1879e',
                        'label' => 'End Date/Time',
                        'name' => 'end_datetime',
                        'type' => 'date_time_picker',
                        'instructions' => '',
                        'required' => 1,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'display_format' => 'F j, Y g:i a',
                        'return_format' => 'U',
                        'first_day' => 0,
                    ),
                    array(
                        'key' => 'field_5ee7d04318795',
                        'label' => 'Event Location',
                        'name' => 'event_location',
                        'type' => 'group',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'layout' => 'block',
                        'sub_fields' => array(
                            array(
                                'key' => 'field_5ee7d09018796',
                                'label' => 'Venue Name',
                                'name' => 'venue',
                                'type' => 'text',
                                'instructions' => 'The name of the Venue',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'default_value' => '',
                                'placeholder' => '',
                                'prepend' => '',
                                'append' => '',
                                'maxlength' => '',
                            ),
                            array(
                                'key' => 'field_5ee7d0b218797',
                                'label' => 'Venue Address',
                                'name' => 'address',
                                'type' => 'group',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'layout' => 'block',
                                'sub_fields' => array(
                                    array(
                                        'key' => 'field_5ee7d0d618798',
                                        'label' => 'Street Address',
                                        'name' => 'street_address',
                                        'type' => 'text',
                                        'instructions' => 'Full Street address, included unit number if applicable.',
                                        'required' => 0,
                                        'conditional_logic' => 0,
                                        'wrapper' => array(
                                            'width' => '',
                                            'class' => '',
                                            'id' => '',
                                        ),
                                        'default_value' => '',
                                        'placeholder' => '',
                                        'prepend' => '',
                                        'append' => '',
                                        'maxlength' => '',
                                    ),
                                    array(
                                        'key' => 'field_5ee7d0f918799',
                                        'label' => 'City',
                                        'name' => 'city',
                                        'type' => 'text',
                                        'instructions' => 'City where the event will take place',
                                        'required' => 0,
                                        'conditional_logic' => 0,
                                        'wrapper' => array(
                                            'width' => '',
                                            'class' => '',
                                            'id' => '',
                                        ),
                                        'default_value' => '',
                                        'placeholder' => '',
                                        'prepend' => '',
                                        'append' => '',
                                        'maxlength' => '',
                                    ),
                                    array(
                                        'key' => 'field_5ee7d1161879a',
                                        'label' => 'State',
                                        'name' => 'state',
                                        'type' => 'select',
                                        'instructions' => '',
                                        'required' => 0,
                                        'conditional_logic' => 0,
                                        'wrapper' => array(
                                            'width' => '',
                                            'class' => '',
                                            'id' => '',
                                        ),
                                        'choices' => array(
                                            'AL' => 'AL',
                                            'AK' => 'AK',
                                            'AR' => 'AR',
                                            'AZ' => 'AZ',
                                            'CA' => 'CA',
                                            'CO' => 'CO',
                                            'CT' => 'CT',
                                            'DC' => 'DC',
                                            'DE' => 'DE',
                                            'FL' => 'FL',
                                            'GA' => 'GA',
                                            'HI' => 'HI',
                                            'IA' => 'IA',
                                            'ID' => 'ID',
                                            'IL' => 'IL',
                                            'IN' => 'IN',
                                            'KS' => 'KS',
                                            'KY' => 'KY',
                                            'LA' => 'LA',
                                            'MA' => 'MA',
                                            'MD' => 'MD',
                                            'ME' => 'ME',
                                            'MI' => 'MI',
                                            'MN' => 'MN',
                                            'MO' => 'MO',
                                            'MS' => 'MS',
                                            'MT' => 'MT',
                                            'NC' => 'NC',
                                            'NE' => 'NE',
                                            'NH' => 'NH',
                                            'NJ' => 'NJ',
                                            'NM' => 'NM',
                                            'NV' => 'NV',
                                            'NY' => 'NY',
                                            'ND' => 'ND',
                                            'OH' => 'OH',
                                            'OK' => 'OK',
                                            'OR' => 'OR',
                                            'PA' => 'PA',
                                            'RI' => 'RI',
                                            'SC' => 'SC',
                                            'SD' => 'SD',
                                            'TN' => 'TN',
                                            'TX' => 'TX',
                                            'UT' => 'UT',
                                            'VT' => 'VT',
                                            'VA' => 'VA',
                                            'WA' => 'WA',
                                            'WI' => 'WI',
                                            'WV' => 'WV',
                                            'WY' => 'WY',
                                        ),
                                        'default_value' => false,
                                        'allow_null' => 0,
                                        'multiple' => 0,
                                        'ui' => 0,
                                        'return_format' => 'value',
                                        'ajax' => 0,
                                        'placeholder' => '',
                                    ),
                                    array(
                                        'key' => 'field_5ee7d1c31879b',
                                        'label' => 'Postal Code',
                                        'name' => 'postal_code',
                                        'type' => 'text',
                                        'instructions' => '',
                                        'required' => 0,
                                        'conditional_logic' => 0,
                                        'wrapper' => array(
                                            'width' => '',
                                            'class' => '',
                                            'id' => '',
                                        ),
                                        'default_value' => '',
                                        'placeholder' => '',
                                        'prepend' => '',
                                        'append' => '',
                                        'maxlength' => '',
                                    ),
                                ),
                            ),
                        ),
                    ),
                    array(
                        'key' => 'field_5ee7d1fd1879c',
                        'label' => 'Featured Image',
                        'name' => 'featured_image',
                        'type' => 'image',
                        'instructions' => 'The primary associated with the event',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'return_format' => 'array',
                        'preview_size' => 'medium',
                        'library' => 'all',
                        'min_width' => '',
                        'min_height' => '',
                        'min_size' => '',
                        'max_width' => '',
                        'max_height' => '',
                        'max_size' => '',
                        'mime_types' => '',
                    ),
                ),
            ),
        ),
        'location' => array(
            array(
                array(
                    'param' => 'options_page',
                    'operator' => '==',
                    'value' => 'events-settings',
                ),
            ),
            array(
                array(
                    'param' => 'post_type',
                    'operator' => '==',
                    'value' => 'post',
                ),
            ),
        ),
        'menu_order' => 0,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => '',
        'active' => true,
        'description' => '',
        'show_in_graphql' => 1,
        'graphql_field_name' => 'events',
    ));
    
    endif;