<?php
if( function_exists('acf_add_local_field_group') ):

    acf_add_local_field_group(array(
        'key' => 'group_5ee7c62d4c8e2',
        'title' => 'Books',
        'fields' => array(
            array(
                'key' => 'field_5ee7c6ba4f360',
                'label' => 'Book',
                'name' => 'books',
                'type' => 'repeater',
                'instructions' => 'Add or Remove Books that should be displayed on the book page',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'show_in_graphql' => 1,
                'collapsed' => 'field_5ee7c6f54f361',
                'min' => 0,
                'max' => 0,
                'layout' => 'block',
                'button_label' => 'Add Book',
                'sub_fields' => array(
                    array(
                        'key' => 'field_5ef68b3b9b3a8',
                        'label' => 'ID',
                        'name' => 'id',
                        'type' => 'text',
                        'instructions' => 'Read Only !! The unique identifier of this book object',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'show_in_graphql' => 1,
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                    ),
                    array(
                        'key' => 'field_5ee7c6f54f361',
                        'label' => 'Book Title',
                        'name' => 'book_title',
                        'type' => 'wysiwyg',
                        'instructions' => 'The Official Published Title of the book, including Subtitle, if provided.',
                        'required' => 1,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'tabs' => 'all',
                        'toolbar' => 'basic',
                        'media_upload' => 0,
                        'delay' => 0,
                    ),
                    array(
                        'key' => 'field_5ee7c72a4f362',
                        'label' => 'Authors',
                        'name' => 'authors',
                        'type' => 'repeater',
                        'instructions' => 'Include at least one author for the publication. Co-authors should be added after the primary author',
                        'required' => 1,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'collapsed' => 'field_5ee7c75d4f363',
                        'min' => 1,
                        'max' => 0,
                        'layout' => 'block',
                        'button_label' => 'Add Author',
                        'sub_fields' => array(
                            array(
                                'key' => 'field_5ee7c75d4f363',
                                'label' => 'Author',
                                'name' => 'author',
                                'type' => 'group',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'layout' => 'block',
                                'sub_fields' => array(
                                    array(
                                        'key' => 'field_5ee7c7704f364',
                                        'label' => 'Name',
                                        'name' => 'name',
                                        'type' => 'text',
                                        'instructions' => 'Include the full name of the author as published with the book. Only include Titles (Dr., Mrs, etc) and Suffices (Jr, PhD, EdD, etc) if part of the publication.',
                                        'required' => 0,
                                        'conditional_logic' => 0,
                                        'wrapper' => array(
                                            'width' => '',
                                            'class' => '',
                                            'id' => '',
                                        ),
                                        'default_value' => '',
                                        'placeholder' => '',
                                        'prepend' => '',
                                        'append' => '',
                                        'maxlength' => '',
                                    ),
                                    array(
                                        'key' => 'field_5ee7c7e04f365',
                                        'label' => 'Url',
                                        'name' => 'url',
                                        'type' => 'url',
                                        'instructions' => 'Not required. But include a url relevant to this author, such as a portfolio, blog, or other professional link',
                                        'required' => 0,
                                        'conditional_logic' => 0,
                                        'wrapper' => array(
                                            'width' => '',
                                            'class' => '',
                                            'id' => '',
                                        ),
                                        'default_value' => '',
                                        'placeholder' => '',
                                    ),
                                    array(
                                        'key' => 'field_5ee7c82b4f366',
                                        'label' => 'Email',
                                        'name' => 'email',
                                        'type' => 'email',
                                        'instructions' => 'Not Required. The email address for this author as it pertains to this publication.',
                                        'required' => 0,
                                        'conditional_logic' => 0,
                                        'wrapper' => array(
                                            'width' => '',
                                            'class' => '',
                                            'id' => '',
                                        ),
                                        'default_value' => '',
                                        'placeholder' => '',
                                        'prepend' => '',
                                        'append' => '',
                                    ),
                                    array(
                                        'key' => 'field_5ee7c8614f367',
                                        'label' => 'Short Bio',
                                        'name' => 'short_bio',
                                        'type' => 'wysiwyg',
                                        'instructions' => 'A short bio for this author as it pertains to this publication.',
                                        'required' => 0,
                                        'conditional_logic' => 0,
                                        'wrapper' => array(
                                            'width' => '',
                                            'class' => '',
                                            'id' => '',
                                        ),
                                        'default_value' => '',
                                        'tabs' => 'all',
                                        'toolbar' => 'full',
                                        'media_upload' => 1,
                                        'delay' => 0,
                                    ),
                                    array(
                                        'key' => 'field_5ee7c87b4f368',
                                        'label' => 'Profile Image',
                                        'name' => 'profile_image',
                                        'type' => 'image',
                                        'instructions' => 'An Image for this author as it pertains to this publication.',
                                        'required' => 0,
                                        'conditional_logic' => 0,
                                        'wrapper' => array(
                                            'width' => '',
                                            'class' => '',
                                            'id' => '',
                                        ),
                                        'return_format' => 'array',
                                        'preview_size' => 'medium',
                                        'library' => 'all',
                                        'min_width' => '',
                                        'min_height' => '',
                                        'min_size' => '',
                                        'max_width' => '',
                                        'max_height' => '',
                                        'max_size' => '',
                                        'mime_types' => 'jpg,png,webp',
                                    ),
                                ),
                            ),
                        ),
                    ),
                    array(
                        'key' => 'field_5ee7c9034f36a',
                        'label' => 'Publisher',
                        'name' => 'publisher',
                        'type' => 'text',
                        'instructions' => 'The name and address of the publishing company as to be listed within the publishers page of the book. For example: Zondervan, Grand Rapids, MI',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                    ),
                    array(
                        'key' => 'field_5ee7c8e94f369',
                        'label' => 'Cover Image',
                        'name' => 'cover_image',
                        'type' => 'image',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'return_format' => 'array',
                        'preview_size' => 'medium',
                        'library' => 'all',
                        'min_width' => '',
                        'min_height' => '',
                        'min_size' => '',
                        'max_width' => '',
                        'max_height' => '',
                        'max_size' => '',
                        'mime_types' => '',
                    ),
                    array(
                        'key' => 'field_5ee7cb174f36f',
                        'label' => 'Excerpt',
                        'name' => 'excerpt',
                        'type' => 'wysiwyg',
                        'instructions' => 'Separate snippets with a new line if necessary.',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'tabs' => 'all',
                        'toolbar' => 'basic',
                        'media_upload' => 0,
                        'delay' => 0,
                    ),
                    array(
                        'key' => 'field_5ee7c9ab4f36c',
                        'label' => 'ISBN',
                        'name' => 'isbn',
                        'type' => 'text',
                        'instructions' => 'The ISBN of the publication',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                    ),
                    array(
                        'key' => 'field_5ee7cdb24f377',
                        'label' => 'Edition',
                        'name' => 'edition',
                        'type' => 'text',
                        'instructions' => 'The edition of the work, if any.',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                    ),
                    array(
                        'key' => 'field_5ee7c9cd4f36d',
                        'label' => 'Product Urls',
                        'name' => 'product_urls',
                        'type' => 'repeater',
                        'instructions' => 'Include URLs of online locations where the book can be purchased',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'collapsed' => 'field_5ee7cacb4f36e',
                        'min' => 0,
                        'max' => 0,
                        'layout' => 'block',
                        'button_label' => 'Add Url',
                        'sub_fields' => array(
                            array(
                                'key' => 'field_5ee7cacb4f36e',
                                'label' => 'product_url',
                                'name' => 'product_url',
                                'type' => 'url',
                                'instructions' => 'Be sure to include any tracking parameters that the online retailer provides for attributing the source of the link to your site.',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'default_value' => '',
                                'placeholder' => '',
                            ),
                        ),
                    ),
                    array(
                        'key' => 'field_5ee7c95c4f36b',
                        'label' => 'Date Available for Purchase',
                        'name' => 'date_available_for_purchase',
                        'type' => 'date_picker',
                        'instructions' => 'The date the book can be purchased online or in stores.',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'display_format' => 'F j, Y',
                        'return_format' => 'U',
                        'first_day' => 0,
                    ),
                    array(
                        'key' => 'field_5ee7cb4a4f370',
                        'label' => 'Endorsements & Reviews',
                        'name' => 'endorsements',
                        'type' => 'repeater',
                        'instructions' => 'For displaying endorsements for this publication',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'collapsed' => 'field_5ee7cb834f371',
                        'min' => 0,
                        'max' => 0,
                        'layout' => 'block',
                        'button_label' => 'Add Endorsement',
                        'sub_fields' => array(
                            array(
                                'key' => 'field_5ee7cb834f371',
                                'label' => 'Endorsement/Review',
                                'name' => 'endorsement',
                                'type' => 'group',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'layout' => 'block',
                                'sub_fields' => array(
                                    array(
                                        'key' => 'field_5ee7cbad4f372',
                                        'label' => 'Endorsement Text',
                                        'name' => 'endorsement_text',
                                        'type' => 'wysiwyg',
                                        'instructions' => 'The snippet of the endorsement or review',
                                        'required' => 0,
                                        'conditional_logic' => 0,
                                        'wrapper' => array(
                                            'width' => '',
                                            'class' => '',
                                            'id' => '',
                                        ),
                                        'default_value' => '',
                                        'tabs' => 'all',
                                        'toolbar' => 'full',
                                        'media_upload' => 0,
                                        'delay' => 0,
                                    ),
                                    array(
                                        'key' => 'field_5ee7ccc84f373',
                                        'label' => 'Rating',
                                        'name' => 'rating',
                                        'type' => 'number',
                                        'instructions' => 'The rating associated with the endorsement or review',
                                        'required' => 0,
                                        'conditional_logic' => 0,
                                        'wrapper' => array(
                                            'width' => '',
                                            'class' => '',
                                            'id' => '',
                                        ),
                                        'default_value' => 5,
                                        'placeholder' => '',
                                        'prepend' => '',
                                        'append' => '',
                                        'min' => 1,
                                        'max' => 5,
                                        'step' => 1,
                                    ),
                                    array(
                                        'key' => 'field_5ee7ccec4f374',
                                        'label' => 'Reviewer Name',
                                        'name' => 'reviewer_name',
                                        'type' => 'text',
                                        'instructions' => 'The full name and title of the person leaving the review',
                                        'required' => 0,
                                        'conditional_logic' => 0,
                                        'wrapper' => array(
                                            'width' => '',
                                            'class' => '',
                                            'id' => '',
                                        ),
                                        'default_value' => '',
                                        'placeholder' => '',
                                        'prepend' => '',
                                        'append' => '',
                                        'maxlength' => '',
                                    ),
                                    array(
                                        'key' => 'field_5ee7cd474f375',
                                        'label' => 'Reviewer Organization',
                                        'name' => 'reviewer_organization',
                                        'type' => 'text',
                                        'instructions' => 'The full name of the organization, if any, where the endorsement was printed or that the reviewer represents.',
                                        'required' => 0,
                                        'conditional_logic' => 0,
                                        'wrapper' => array(
                                            'width' => '',
                                            'class' => '',
                                            'id' => '',
                                        ),
                                        'default_value' => '',
                                        'placeholder' => '',
                                        'prepend' => '',
                                        'append' => '',
                                        'maxlength' => '',
                                    ),
                                    array(
                                        'key' => 'field_5ee7cd794f376',
                                        'label' => 'Review URL',
                                        'name' => 'review_url',
                                        'type' => 'url',
                                        'instructions' => 'Either the URL where the full review can be read, or the url of the organization associated with the review above.',
                                        'required' => 0,
                                        'conditional_logic' => 0,
                                        'wrapper' => array(
                                            'width' => '',
                                            'class' => '',
                                            'id' => '',
                                        ),
                                        'default_value' => '',
                                        'placeholder' => '',
                                    ),
                                ),
                            ),
                        ),
                    ),
                    array(
                        'key' => 'field_5eed0c30a8813',
                        'label' => 'Is Canonical',
                        'name' => 'is_canonical',
                        'type' => 'true_false',
                        'instructions' => 'Only Check This Box if you intend the content on the Wordpress site to be the canonical version. Otherwise, if this content is being exported to another site, the external site will be considered canonical.',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'show_in_graphql' => 1,
                        'message' => '',
                        'default_value' => 0,
                        'ui' => 0,
                        'ui_on_text' => '',
                        'ui_off_text' => '',
                    ),
                    array(
                        'key' => 'field_5ef68f799b3a9',
                        'label' => 'slug',
                        'name' => 'slug',
                        'type' => 'text',
                        'instructions' => 'The endpoint for book on the author\'s website. For example, if the book title is "In His Image", a good slug would be "in-his-image". Please only use lowercase letters, numbers, dashes, and (if you must) underscores.',
                        'required' => 1,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'show_in_graphql' => 1,
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                    ),
                ),
            ),
        ),
        'location' => array(
            array(
                array(
                    'param' => 'options_page',
                    'operator' => '==',
                    'value' => 'books-settings',
                ),
            ),
            array(
                array(
                    'param' => 'post_type',
                    'operator' => '==',
                    'value' => 'post',
                ),
            ),
        ),
        'menu_order' => 0,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => '',
        'active' => true,
        'description' => '',
        'show_in_graphql' => 1,
        'graphql_field_name' => 'books',
    ));
    
    endif;